package chapter09.alpha;

import org.drools.devguide.eshop.model.Customer;
import org.drools.devguide.eshop.model.Customer.Category;

rule "Sample Rule 1"
when
    $c: Customer(age > 30, category == Category.GOLD)
then
    channels["gold-customer-channel"].send($c);
end

rule "Sample Rule 2"
when
    $c: Customer(age > 30, category == Category.SILVER)
then
    channels["silver-customer-channel"].send($c);
end