package rules;

import org.drools.devguide.eshop.model.Customer;
import org.drools.devguide.eshop.model.Order;
import org.drools.devguide.eshop.model.Discount;


rule "Bronze Customers - 5% Discount"
    when
        $o: Order( $customer: customer, discount == null )
        $c: Customer( category == Category.BRONZE, this == $customer )
    then
        $o.setDiscount(new Discount(5.0));
        update($o);
end